### ISSUE TITLE
async void methods break ASP.NET 4.5

### ISSUE THREAD

**Issue by dotnetchris** [furier/PersistentObjectCache#1]
PersistentObjectCache's use of ```async void``` such as 

```c# 
T SetObjectAsync<T>(string key, T value...
```

 running under ASP.NET (MVC5 in this case but shouldn't matter) when called results in:

> An asynchronous module or handler completed while an asynchronous operation was still pending.

More information on this can be seen on http://stackoverflow.com/a/17660475/37055

**Comment by dotnetchris** [comment]
@furier can you please ping this thread when you release a new version on https://www.nuget.org/packages/PersistentObjectCache so i can switch back to nuget?

**Comment by furier** [comment]
Will try and remember that. :)

tir. 29. des. 2015 kl. 21.16 skrev Chris Marisic <notifications@github.com>:

**Comment by dotnetchris** [comment]
Can you please roll out a new release to nuget? The release that's out there is pretty much unusable for the current edition .NET

**Comment by furier** [comment]
Done
